### ISSUE TITLE
some invalid emails are not filtered through this package

### ISSUE THREAD

**Issue by DavidHwu** [JoshData/python-email-validator#1]
http://www.fileformat.info/info/unicode/char/2014/index.htm
EM DASH

For example, EM DASH is not filtered out... reading the standards I believe that it should be.
This email for example is being rejected by sendwithus.com but pass this package validation.
foo—bar@hotmail.com

**Comment by JoshData** [comment]
Hi David. Why do you think it should be ruled out?

It will require MTAs on the path to all support `SMTPUTF8` (per the returned `smtputf8` flag).

**Comment by DavidHwu** [comment]
Thanks Josh!  
I found out that neither sendwithus or sendgrid service provider doesn't support unicode (EM DASH) in the actual email themselves... thats the root cause.
Standards seems to have been changing and does actually enable support of unicode character actual emails. 

Kindly one more case study:
paulo.baleiz\xe3o@sapo.pt

This seem passed your package, and I think its a valid email address.  Kindly confirm.
Thanks again

**Comment by DavidHwu** [comment]
I see the flag in the validate_email() to rule out scenarios that does not support unicode as part of the email.  Correcting my original statement about EM DASH as this standard has not been adapted in many of the email service providers (ie. sendwithus.com and sendgrid).
