### ISSUE TITLE
Encoding issue in pip package

### ISSUE THREAD

**Issue by todpunk** [JoshData/python-email-validator#10]
There was a fix for the issue the pip package has in this issue: https://github.com/JoshData/python-email-validator/issues/5

This needs to be pushed up to pip (probably needs a minor version number increase as well).

**Comment by JoshData** [comment]
Thanks for the reminder. I pushed 1.0.1 (6b7e3e362eaeb2b1ae4281f4d18421bd31dad3fb) to pypi just now.

**Comment by todpunk** [comment]
Confirmed that this fixes the error with the pip package.

**Comment by JoshData** [comment]
Thanks for confirming!
