### ISSUE TITLE
Please consider an alternative license

### ISSUE THREAD

**Issue by musicinmybrain** [JoshData/python-email-validator#113]
Fedora Linux has reclassified the [`CC0-1.0`](https://spdx.org/licenses/CC0-1.0.html) license as [allowed for content only](https://lwn.net/ml/fedora-legal/CAC1cPGw1xScGAXo-0NRs92zFB7ptRxTt=oCYi0BxfZDfAgUtYQ@mail.gmail.com/) due to concerns about patent-related language.

While the [`python-email-validator`](https://src.fedoraproject.org/rpms/python-email-validator) package can remain in Fedora Linux under a [blanket exception](https://gitlab.com/fedora/legal/fedora-license-data/-/issues/91#note_1151947383) for code files in Fedora packages prior to 2022-08-01, it would still be much better from Fedora’s perspective if the package could be offered under a different license. Some widely-accepted extremely-permissive licenses include [`0BSD`](https://spdx.org/licenses/0BSD.html), [`MIT-0`](https://spdx.org/licenses/MIT-0.html), and [`Unlicense`](https://spdx.org/licenses/Unlicense.html).

I suspect there are other users out there for whom the `CC0-1.0` license is becoming a problem.

**Comment by JoshData** [comment]
Thanks. This is on my to-do now. My preference is Unlicense but the main website for it is down which is somewhat concerning, so I'm thinking through the options.

**Comment by JoshData** [comment]
Done!

**Comment by musicinmybrain** [comment]
Wonderful, thank you! When you tag a new release, I’ll make sure our package is updated.

**Comment by PidgeyBE** [comment]
Would it be possible to create a (patch) release with this change included?

**Comment by JoshData** [comment]
Done. Thanks for the reminder. 😀
