### ISSUE TITLE
Doesn't handle EMOJI domains correctly.

### ISSUE THREAD

**Issue by pjsg** [JoshData/python-email-validator#12]
For example:   

```
validate_email(u'philip@👍👍.ws')
Traceback (most recent call last):
...
    raise EmailSyntaxError("The domain name %s contains invalid characters (%s)." % (domain, str(e)))
EmailSyntaxError: The domain name \U0001f44d\U0001f44d.ws contains invalid characters (Codepoint U+1F44D at position 1 of u'\U0001f44d\U0001f44d' not allowed).
```

Note that http://👍👍.ws does actually work (although github doesn't linkify it). There are a few TLDs that permit registering emoji domains.

**Comment by JoshData** [comment]
Hi,

Huh. Well. These things are hard to diagnose so bear with me here...

1) The fact that it works in some places doesn't mean it _should_ work. (There could be an IDNA2003/IDNA 2008 difference, for instance, although I don't think that's the case here.)
2) If this is a bug, it's in the https://github.com/kjd/idna module.
3) The problem could be either in [UTS46 mapping](http://www.unicode.org/reports/tr46/) or in the set of permissible IDNA 2008 characters (which are separate things).
4) The character may be defined in a newer version of Unicode than the IDNA library knows about.

So this is difficult to figure out!

**Comment by pjsg** [comment]
There is quite an interesting discuission about Emoji domains at: http://archives.miloush.net/michkap/archive/2012/02/27/10273315.html

The tl;dr is that they appear to be permitted by IDNA2003 and permitted in compatibility mode in IDNA2008 but *should* go away after that. Of course, this requires that all the registrars get the message (and that all clients get the message to not permit them). 

My inclination is to convert to punycode and then do the lookup, and treat it as valid if it works. 

I agree that this stuff is a nightmare.

**Comment by JoshData** [comment]
Fantastic link. (I'll add it to the README.)

I'm inclined to close the issue, since it seems like it was a mistake for `ws` to allow you to register that domain. Agreed?

**Comment by pjsg** [comment]
I'm fine with that -- at least until it becomes a real problem!
