### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by PanderMusubi** [JoshData/python-email-validator#123]
The following error is correct:

    >>> validate_email('john + @john.com', check_deliverability=False)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/pander/.local/lib/python3.10/site-packages/email_validator/validate_email.py", line 71, in validate_email
        local_part_info = validate_email_local_part(local_part,
      File "/home/pander/.local/lib/python3.10/site-packages/email_validator/syntax.py", line 222, in validate_email_local_part
        raise EmailSyntaxError("The email address contains invalid characters before the @-sign: " + ", ".join(sorted(bad_chars)) + ".")
    email_validator.exceptions_types.EmailSyntaxError: The email address contains invalid characters before the @-sign: SPACE.

However, you get the same/similar error for:
- `john @john.com`
- ` john@john.com`
- ` john@john.com`
- `john@ john.com`
- `john@john .com`
- `john@john.com `

about space plus space even thought there is only one space.

**Comment by PanderMusubi** [comment]
Or is the `" + "` not part of the reported error and only `SPACE` is?

**Comment by JoshData** [comment]
Hi. I think you may be misreading the Python output.

The error message is:

> The email address contains invalid characters before the @-sign: SPACE.

The line above it (which contains `" + "`) is a snippet of the library's source code as a part of the Traceback. That line is Python code that constructs the message. The characters on that line are library source code, not invalid characters in the email address.

Does that help?

**Comment by PanderMusubi** [comment]
Yes, thanks.

Out of scope but for context (in case somebody else has similar challenge) in Flask you can add a filter to strip an email address from spaces at the end or beginning. This will prevent failing of this email validation if you are using `render_form` macro.

        def filter_email(form, field):
            if field is None:
                return field
            return field.strip()
