### ISSUE TITLE
Vulnerability in `dnspython`

### ISSUE THREAD

**Issue by nghazali** [JoshData/python-email-validator#130]
Hi there, we use `python-email-validator` indirectly. We recently had a vulnerability (https://security.snyk.io/vuln/SNYK-PYTHON-DNSPYTHON-6241713)  related to `dnspython `, which your component uses. The suggested solution is bumping the version to `dnspython 2.6.1`

I tried to raise a PR, but unfortunately, it failed because of the authorisation issue. Please update the `dnspython` version to `2.6.1` to make the product more secure.

**Comment by JoshData** [comment]
This project doesn't specify a particular version of dnspython so I don't think there is anything for me to do here.

**Comment by nghazali** [comment]
Thank you for updating the `dnspython` version. It looks like it was updated 3 days ago:
<img width="718" alt="Screenshot 2024-02-29 at 5 26 05 pm" src="https://github.com/JoshData/python-email-validator/assets/36830944/64ae8e36-5356-460f-8a7e-f9f5ef86f199">

**Comment by JoshData** [comment]
Yeah I realized after that it's mentioned in the test requirements file. You'd only use this file if you are running the tests. For a normal installation this file has no impact. I'm not even sure if the file is present in a. normal installation.

**Comment by Zaczero** [comment]
If that helps, here is the dependency list from a normal installation:

```txt
email-validator 2.1.1 A robust email address syntax and deliverability validation library.
├── dnspython >=2.0.0
└── idna >=2.0.0
```
