### ISSUE TITLE
`email=` in `validate_email()` raises `TypeError`

### ISSUE THREAD

**Issue by aryadovoy** [JoshData/python-email-validator#131]
It's not working while I use `email=`, what is the problem?

Code:
```python
from email_validator import validate_email


validate_email(email="user@test.com",
    check_deliverability=True,
    test_environment=False,
)
```

Error:
```shell
TypeError: validate_email() got some positional-only arguments passed as keyword arguments: 'email'
```

Python version: 3.12.1
email-validator version: 2.1.1

**Comment by Sanyam-jain30** [comment]
The validate_email function in this library defines the email parameter as positional-only. This means it can only be passed directly by its position and not by keyword using email=.

Correct Code:
```
from email_validator import validate_email


validate_email("user@test.com",
    check_deliverability=True,
    test_environment=False,
)
```

Reference:
https://pypi.org/project/email-validator/

**Comment by aryadovoy** [comment]
@Sanyam-jain30, but why? On previous version it worked fine.

**Comment by Sanyam-jain30** [comment]
I think you were using the validate_email version < 2.10 because, in the versions after 2.10, they converted the email to positional-only.

![image](https://github.com/JoshData/python-email-validator/assets/78720027/e7893cdb-74b7-49ae-a299-a71f664eaa74)

**Comment by JoshData** [comment]
It's also mentioned in the CHANGELOG file.
