### ISSUE TITLE
Tag each release

### ISSUE THREAD

**Issue by deogracia** [JoshData/python-email-validator#14]
Hi!

Thanks for your work :D 

You should create a tag in order to make the 2 releases (1.0 & 1.0.1) you already made stand out.

**Comment by JoshData** [comment]
Great idea - I just [tagged 1.0.3](https://github.com/JoshData/python-email-validator/tree/v1.0.3).

**Comment by jab** [comment]
Thanks @JoshData.
Would you be interested in summarizing any notable changes in this release? Users currently have to go through the commits to see what's changed.

You can do this on your GitHub Releases page or / as well as in a CHANGELOG.md: https://github.com/JoshData/python-email-validator/releases

http://keepachangelog.com/

**Comment by JoshData** [comment]
There have been so few changes it hasn't been worth adding a CHANGELOG. But I've added a release with a short explanation. Thanks.
