### ISSUE TITLE
also provide tar-ball on pypi

### ISSUE THREAD

**Issue by arunpersaud** [JoshData/python-email-validator#18]
Hi

if possible, please also provide a tar-ball on pypi. This helps, for example, when trying to package the module for a linux distribution.

Thanks

Arun

**Comment by JoshData** [comment]
Tell me what commands to run and I'll do 'em. :)

**Comment by arunpersaud** [comment]
Hi

unfortunately, I never uploaded anything to pypi myself, but I found the following link via google

https://perceval.readthedocs.io/en/latest/howto_pkg.html

It seems to suggest the following commands 

create package:
python3 setup.py bdist_wheel
python3 setup.py sdist

upload seems to be via (in this case to the pypi test repository):
python setup.py register -r pypitest
python setup.py sdist upload -r pypitest
python setup.py bdist_wheel upload -r pypitest

or to pypi via
python setup.py sdist upload -r pypi
python setup.py bdist_wheel upload -r pypi

HTH

Arun

**Comment by JoshData** [comment]
Sorry for the delay! Doing it now!
