### ISSUE TITLE
Invalid email: invalid domain string after '@' character

### ISSUE THREAD

**Issue by VKen** [JoshData/python-email-validator#2]
It's pretty amazing that it caught many invalid emails that I threw at this validator.

The only one that it didn't catch, is something like this `abc@.example.com`
The validator ignored the beginning `.` that was in front of the domain.

The above invalid email was, however, caught by the `boto` library i was using with AWS.

**Comment by JoshData** [comment]
Awesome. Really appreciate the bug report. I'll take a look.
