### ISSUE TITLE
Python 2 and 3 validate emails differently

### ISSUE THREAD

**Issue by claweyenuk** [JoshData/python-email-validator#23]
I wrote a test wrapper around the test_pass.txt file (converted to a csv in my local copy) and saw several failures in Python 2 that passed in Python 3.  I tracked it down to an issue with Python 2's regex with utf-8 characters.

This best illustrates the issue:

Python 2:

    >>> import re
    >>> re.compile(u"[\x80-\U0010ffff]", re.DEBUG)
    in
      range (128, 56319)
      literal 57343
    <_sre.SRE_Pattern object at 0x000000000599B2D0>

Python 3:

    >>> import re
    >>> re.compile(u"[\x80-\U0010ffff]", re.DEBUG)
    IN
      RANGE (128, 1114111)
    re.compile('[\x80-\U0010ffff]', re.DEBUG)

The unicode character \U0010ffff should be 1114111, but Python 2 interprets the unicode characater as 2 characters, and so it does not recognize the full range.  The test with the local part set to u'my\uff0ename' fails because of this issue.

I have been unable to get a regex that works so far.  I suspect it's related to this:

    unichr(0x0010ffff)
    Traceback (most recent call last):
      Python Shell, prompt 114, line 1
    ValueError: unichr() arg not in range(0x10000) (narrow Python build)

**Comment by claweyenuk** [comment]
Here is the testing code I have so far: https://github.com/JoshData/python-email-validator/compare/master...claweyenuk:master

**Comment by JoshData** [comment]
Interesting. Can you paste one of the test addresses that come out differently in Py2/Py3?

**Comment by claweyenuk** [comment]
One is here: https://github.com/JoshData/python-email-validator/compare/master...claweyenuk:master#diff-929733c06297dc2be4161852db3fe609R16

Hopefully it pastes correctly: `my．name@domain.com`

**Comment by JoshData** [comment]
And what's the output you're getting from Py2?

**Comment by claweyenuk** [comment]
This email is valid in Python 3.  In Python 2 it returns this error:

https://github.com/JoshData/python-email-validator/blob/master/email_validator/__init__.py#L133

"The email address contains invalid characters before the @-sign"

The reason is the regex on line 129 (a few lines up) fails because it's only matching unicode characters in `range (128, 56319)` and the unicode character is 65294 (0xff0e)

**Comment by JoshData** [comment]
I think this may have to do with "narrow" vs "wide" builds of Python:

https://www.python.org/dev/peps/pep-0261/

On a narrow build (indicated in the error message in one of your code blocks above), Python simply doesn't represent four-byte unicode characters. Instead it encodes them as two two-byte characters called a surrogate pair. So the regular expression is behaving correctly in so far as only two-byte unicode characters are recognized in narrow-build Python regexes.

This is actually already noted in my README, although I totally forgot about it:

> UCS-4 support required for Python 2.7
> 
> Note that when using Python 2.7, it is required that it was built with UCS-4 support (see here); otherwise emails with unicode characters outside of the BMP (Basic Multilingual Plane) will not validate correctly.

To be honest, it's not obvious to me that the narrow build is wrong. The email address might be valid, but narrow-build Python may not be able to correctly represent the email address in memory, and if it can't, then who knows what is being validated.

That said, a fix would be to replace the regular expression with a new test that can understand surrogate pairs. But until there's a real email address in use that this library fails on, I'm inclined to just let the tests remain as they are.

**Comment by claweyenuk** [comment]
Ah, thanks for pointing that out, I completely missed it.

I also check out the server the code is running on and it looks like the Python build there is wide, I'm working on a windows laptop, I wonder if it's mainly a windows issue.

I did some poking around on the string, and it looks valid - the length is correct and the values for `[ord(c) for c in local]` are the same for Python 2 narrow build and Python 3.  So the string looks valid, it's just the regex that isn't working.  I implemented a fix that has the tests passing on both Python 2 narrow builds and Python 3 builds, which is in PR #24

**Comment by JoshData** [comment]
Hmm. I'm confused by how the strings would be the same in a narrow build and a wide build if that was the problem with the regular expression.

**Comment by claweyenuk** [comment]
Ah, good observation!  I had drawn some wrong conclusions.

The string `u"\uff0e"` (65294) is 1 character in both my narrow build and my wide build.  The max character, `u"\U0010ffff"` (1114111) is 2 characters in the narrow build and 1 character in the wide build.  So yes, they are different.

The narrow builds correctly interprets strings with characters up to `u"\uffff"` (65535).  The regex has a character above that limit and it breaks down into 2 characters - and the way it breaks down it allows characters up to 56319.  I was testing with the character 65294, which falls above what the regex allows, 56319, but below the limit for narrow builds, 65535.

So the PR I had only helped a small character range.  I think this problem might just be too deep in Python narrow builds to worry about.

**Comment by claweyenuk** [comment]
Closing this since this was a false alarm
