### ISSUE TITLE
Does this actually check deliverability?

### ISSUE THREAD

**Issue by etayluz** [JoshData/python-email-validator#27]
I checked my own gmail address vs a fake gmail addresses.

Both returned the same result.

Does this library actually check deliverability?

**Comment by JoshData** [comment]
The deliverability check is that the domain name in the email address resolves. It's discussed further in the README:

> The validator checks that the domain name in the email address resolves. There is nothing to be gained by trying to actually contact an SMTP server, so that's not done here. For privacy, security, and practicality reasons servers are good at not giving away whether an address is deliverable or not: email addresses that appear to accept mail at first can bounce mail after a delay, and bounced mail may indicate a temporary failure of a good email address (sometimes an intentional failure, like greylisting).
