### ISSUE TITLE
the version available on https://pypi.org/project/email_validator/#files is more than a year out of date

### ISSUE THREAD

**Issue by serbant** [JoshData/python-email-validator#29]
![image](https://user-images.githubusercontent.com/1781964/56318879-03f36100-6115-11e9-974d-f79a94d6bf17.png)

**Comment by claweyenuk** [comment]
My guess it's because there's nothing to really update.  9 commits to master since the 1.0.3 release and none look too important.

**Comment by serbant** [comment]
the timeout parameter is not available in the version on pypi

**Comment by JoshData** [comment]
Thanks folks. I've updated it! See https://pypi.org/project/email-validator/. :)

**Comment by samuelcolvin** [comment]
this can be closed.
