### ISSUE TITLE
local-part normalization

### ISSUE THREAD

**Issue by jab** [JoshData/python-email-validator#3]
First off, thanks for releasing this, it's fantastic.

I'm wondering about further normalization of the [local part](https://en.wikipedia.org/wiki/Email_address#Local-part_normalization). email_validator currently performs as much normalization as it can without provider-specific information, e.g. lowercasing the domain.

But (as you know) [many](https://mail.google.com) [popular](https://mail.yahoo.com) [email](https://hotmail.com) [providers](https://mail.icloud.com) are completely case-insensitive, [some](https://support.google.com/mail/answer/10313?hl=en) are dot-insensitive, and still more support [disposable email addresses](https://en.wikipedia.org/wiki/Disposable_email_address) via [sub-addressing](https://en.wikipedia.org/wiki/Email_address#Sub-addressing) (e.g. foo+tag@bar.com).

Curious if you have any recommendations on how to handle this (ignore and just allow multiple accounts to share the same inbox, normalize and prevent, ...?), or even interest in adding limited support for provider-specific normalization. I notice email_validator already does an MX lookup; from there it could apply e.g. Google Mail-specific local-part normalization rules upon finding a Google Mail-hosted domain, etc.

Thanks again for email_validator and look forward to hearing what you think.

**Comment by JoshData** [comment]
I think that's a losing battle. Every provider might have a long list of different quirks.... I'm not necessarily opposed to adding that here if it can be done reliably, but I don't think it'll be possible.

**Comment by jab** [comment]
Thanks for the quick reply, and I think I get where you're coming from.

But I wonder if adding just a few simple rules for the major providers linked to above (downcasing, +tag stripping, and dot-stripping for gmail) would cover 99% of cases, and so would be worth it?

Or am I misunderstanding the point? If the primary goal of email_validator's normalization is to allow foo@gmail.com to still be able to log in if they type foo@GMAIL.COM, then it would follow that they should still be able to log in if they type FOO@GMAIL.COM. And so local-part normalization seems desirable.

If it's a goal to prevent the owner of foo@gmail.com from creating additional accounts foo+1@gmail.com, foo+2@gmail.com, etc, then this seems useful still.

To be clear, I defer to whatever is considered best practice, or even just your better judgment. I just haven't found any references on best practices for local-part normalization anywhere. Your README is one of the best references I've come across for what it does cover, but it doesn't mention local-part normalization at all. Wonder if you think it's worth a mention, if only to say it's a thing and it's not worth doing because reasons.

**Comment by JoshData** [comment]
> If the primary goal of email_validator's normalization is to allow foo@gmail.com to still be able to log in if they type foo@GMAIL.COM

I hadn't really thought that far ahead. The goal is really validation, and some normalization in the domain part is required to do validation (of IDNA domains in particular). On top of that, [RFC 6532 (internationalized email) section 3.1](https://tools.ietf.org/html/rfc6532#section-3.1) strongly suggests that the whole email address be NFC-normalized prior to going on the wire.

How particular ISPs map multiple email addresses to the same inbox is a separate concern (though I see where you're coming from).

> But I wonder if adding just a few simple rules for the major providers linked to above (downcasing, +tag stripping, and dot-stripping for gmail) would cover 99% of cases, and so would be worth it?

I think it depends. As far as I'm aware, email addresses _can_ be case sensitive. It's just that no sane ISP allows that. But it would be incorrect to downcase addresses if somewhere for someone that would misroute their email (I think). Similarly for +tag stripping, since presumably not every ISP uses +tag aliases and somewhere `a+1` and `a+2` could be different people.

And for ISPs that do support +tags, it would be wrong to "normalize" an address by removing the +tag. Normalization shouldn't change the email address. The idea of +tags is that they are distinct email addresses (e.g. so that different filters can be applied). Checking if two email addresses are owned by the same person would have to be different from normalization, then.

So I think we're back to the beginning. ISP-specific normalization rules isn't a bad idea, especially downcasing the local part, but I still think it's a losing battle to do it reliably.

**Comment by jab** [comment]
I think there may have been a misunderstanding, so just to be clear:

> > But I wonder if adding just a few simple rules for the major providers linked to above... would cover 99% of cases, and so would be worth it?
> 
> I think it depends. As far as I'm aware, email addresses can be case sensitive. It's just that no sane ISP allows that. But it would be incorrect to downcase addresses if somewhere for someone that would misroute their email (I think).

I was proposing the downcase transformation *only for the handful of major providers that are known to be case-insensitive* (and similar with the other proposed transformations).

So the sequence would be:

`1.` Perform MX lookup to obtain email provider domain
`2.` Look up email provider domain in a data structure associating domains with sequences of local-part normalization transformations, for example (and this is literally the entirety of what's being proposed (let's forget about tag stripping)):
```
*.google.com -> [downcase, strip_dots]
*.(yahoo|icloud|hotmail).com -> [downcase]
```
`3.` If the domain is not found in `2`, proceed as we currently do. No local-part normalization is performed.
`4.` If the domain *is* found in `2`, apply the looked-up transformations to the local part before proceeding as we currently do.

Moreover, this could be opted into our out of via a kwarg to the `validate_email` function.

Is this clearer now / does it make any more sense?

Either way, could a mention in the README of local-part normalization (even if only to say it's not supported and link to this discussion) help other users?

**Comment by JoshData** [comment]
Ok. So far downcasing is the only normalization that I think makes sense. Removing periods is likely to cause confusion (I didn't even know that was possible until a few days ago, coincidentally) -- e.g. after a user creates an account, the site shows them their normalized email address without periods, and the user says that's not their email address.

But, still, it would be a major effort to begin collecting domain names that allow downcasing. (I don't think an MX lookup helps here. Just using the domain in the email address would make the most sense.)

What would you want to say in the readme?

**Comment by jab** [comment]
> I don't think an MX lookup helps here. Just using the domain in the email address would make the most sense.

The MX lookup is because e.g. Google Apps for Domains allows people to use Google Mail for their custom domains. So the same normalizations that apply to gmail.com apply to any domain where the MX record points to *.google.com.

> But, still, it would be a major effort to begin collecting domain names that allow downcasing.

Again, the point wouldn't be to provide an exhaustive list; the two rulesets in my previous comment would cover a vast majority of general cases. And you could be real clear about not being interested in covering anything else.

> What would you want to say in the readme?

The readme currently lists "Normalizes email addresses (super important...)" under "Key features". But then makes no mention of local-part normalization.

So as a first cut, it could at least say "We don't support local-part normalization because [reasons](https://github.com/JoshData/python-email-validator/issues/3)" (or "We only support limited local-part normalization..." etc)

**Comment by jab** [comment]
Hey @JoshData, what do you think?

Also, I just came across http://mailgun.github.io/validator-demo/ and noticed that Mailgun's validator considers john@gmail.com invalid because it "Does not meet Gmail minimum local-part length of 6 characters". So it looks like they're taking a pragmatic approach like the one proposed here, i.e. only add the few additional provider-specific rules that cover the vast majority of users. Not so crazy?

**Comment by JoshData** [comment]
Mmmmm ok.

**Comment by prachetos** [comment]
Hi,
 I gave it a shot for gmail, based on the sources I could find. Please check if it suits your need, otherwise close the PR :). I will update the readme in case you decide to merge it. Meanwhile, I will use this for my own use in a project .
function: validate_gmail in __init__.py
https://github.com/JoshData/python-email-validator/pull/8
