### ISSUE TITLE
add tests and CI

### ISSUE THREAD

**Issue by samuelcolvin** [JoshData/python-email-validator#31]
Hi, thank you so much for this package, it's extremely useful. It does the email validation for [pydantic](https://pydantic-docs.helpmanual.io/).

Would you accept a PR to add tests (probably with pytest) and setup CI with travis?

I'd also like to modernise the code to use four spaces if that were allowed to make it easier to work with?

**Comment by JoshData** [comment]
Hey. Thanks. I hadn't seen pydantic before but it looks super useful. Glad to hear you found a use for this package.

Yes, I would definitely accept those changes (but in separate successive pull requests to make review easier). Thanks!

**Comment by samuelcolvin** [comment]
Thanks for accepting my PRs.
