### ISSUE TITLE
Error importing module 'dns'

### ISSUE THREAD

**Issue by j-walker23** [JoshData/python-email-validator#38]
Hello, I'm guessing my problem isn't caused from this library, and is just a sympton.
But after a wasted day, I figured I'd file it in case you had some insight.
Since I have no experience with the python dns module.

Here is the error I'm getting while trying to use this lib. Specifically I get it when `flask-security-too` uses `email_validator`. But below is the error in its simplest form.

<img width="1029" alt="Screen Shot 2020-04-25 at 3 01 22 PM" src="https://user-images.githubusercontent.com/2018885/80290902-0c0db580-8706-11ea-8d7c-26009d82f0a3.png">

**Comment by JoshData** [comment]
Hi. It looks like flask-security-too hasn't properly defined its dependencies because this project's dependencies aren't included in flask-security-too's dependencies, so you're missing the dnspython package (and probably idna as well).

**Comment by j-walker23** [comment]
Thanks man, I really appreciate the help!
