### ISSUE TITLE
IDNA for danish letters

### ISSUE THREAD

**Issue by YnkDK** [JoshData/python-email-validator#4]
First of all, this seems as an awesome package.

But if I try to valdiate an e-mail like: kontakt@rigeligtsmør.dk i get the following error: `The domain name rigeligtsmør.dk contains invalid characters (Codepoint U+00B8 not allowed at position 12 in 'rigeligtsm\xc3\xb8r.dk').`
However, the domain name is legal since: `rigeligtsmør.dk` equals `xn--rigeligtsmr-pgb.dk`

**Comment by JoshData** [comment]
Hey thanks.

Do you have the latest version of this and the `idna` library installed? The address works for me:

	python3 email_validator/__init__.py kontakt@rigeligtsmør.dk
	{
	  "domain": "xn--rigeligtsmr-pgb.dk",
	  "domain_i18n": "rigeligtsmør.dk",
	  "email": "kontakt@rigeligtsmør.dk",
	  "email_ascii": "kontakt@xn--rigeligtsmr-pgb.dk",
	  "local": "kontakt",
	  "mx": [
	    [
	      0,
	      "xn--rigeligtsmr-pgb.dk"
	    ]
	  ],
	  "mx-fallback": false,
	  "smtputf8": false
	}

**Comment by YnkDK** [comment]
I am using Python 2.7, but you pointed me in the correct direction. I was passing a `str` instance to `validate_email`. I have changed my function to be:
```python
def email_type(email):
    if isinstance(email, str):
        email = email.decode('utf8')
    elif not isinstance(email, basestring):
        raise ValueError('E-mail must be a string')
    try:
        v = validate_email(email)
    except EmailNotValidError as e:
        raise ValueError(str(e))
    return v['email']
```

Thanks for this awesome package :-)
