### ISSUE TITLE
Release New Version?

### ISSUE THREAD

**Issue by jamatz** [JoshData/python-email-validator#40]
Are you planning a 1.0.6 anytime soon? I saw that there are some recent bug fixes under commits, but am wondering when those would be packaged. I'm looking to start using this.

Also - would it be possible to include the tarballs for each release on PyPi. For my third party library maintenance, I use pip download --nobinary :all: and the latest version that it's able to grab a .tgz from is 1.0.2.

**Comment by JoshData** [comment]
Doing it now, thanks!

**Comment by jamatz** [comment]
Thanks for the super-fast turnaround!

Would you mind updating https://github.com/JoshData/python-email-validator/releases as well to indicate that 1.0.3 is not the latest release?

**Comment by JoshData** [comment]
Done.
