### ISSUE TITLE
email_validator not found

### ISSUE THREAD

**Issue by Richard-Gosnell** [JoshData/python-email-validator#43]
After pip install and reboot of flask email_validator is still not found. Comes back with 
> ModuleNotFoundError: No module named 'email_validator'
After entering code `from email_validator import validate_email, EmailNotValidError`

**Comment by JoshData** [comment]
Hi. I'm sorry but that sounds like it could be any number of issues related specifically to your environment, which I can't help with.

**Comment by Richard-Gosnell** [comment]
I'm completely sorry. New to python and I installed it to the production enviroment insted of virtual

**Comment by JoshData** [comment]
No worries at all. :)
