### ISSUE TITLE
Deprecation warning under Python 3.8

### ISSUE THREAD

**Issue by wizzardx** [JoshData/python-email-validator#45]
During my tests I'm seeing this:

```python
.../lib/python3.8/site-packages/email_validator/__init__.py:458: DeprecationWarning: please use dns.resolver.resolve() instead
    response = dns.resolver.query(domain, "MX")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

I'm working with email-validator version 1.1.1 from PyPI

**Comment by JoshData** [comment]
This looks to be new in version 2 of dnspython, but version 2 doesn't support Python 2.x, which I'm trying to support in this package for as long as practical. So we can ignore the warning. When we give up Python 2.x support here, we can upgrade to dnspython 2 and address the warning.

**Comment by lucasr300** [comment]
Maybe you can check python's version before running: If is 2.x, use query(), and greater, use resolve().
It can simplify inclusive, on the moment of dropping support for old python releases.

**Comment by JoshData** [comment]
Another approach would be to add a shim: In 2.x, add a `resolve` method to the module that calls `query`. I'd accept a pull request that does either, although I'd prefer the shim because it keeps the 2.x/3.x logic together at the top of the module.
