### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe2'

### ISSUE THREAD

**Issue by erwagasore** [JoshData/python-email-validator#5]
``` python
SyntaxError: Non-ASCII character '\xe2' in file /Users/eugene/.pyenv/versions/mnpl/lib/python2.7/site-packages/email_validator/__init__.py on line 158, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

On line 158 in the __init__.py file there is a comment containing "⒈" which is causing the Error.
I am using python 2.7.10.

Possible solution is to add 
```python 
# -*- coding: utf-8 -*-
```
on the top of the file to ignore the presence of such characters. In python 3.4 the encoding is utf-8 by default but in version 2.7 it is not the case

**Comment by JoshData** [comment]
Hey thanks. Would you submit a PR adding the coding line?

**Comment by erwagasore** [comment]
Solved: Pull Request https://github.com/JoshData/python-email-validator/pull/7
