### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by alifa2try** [JoshData/python-email-validator#53]
I am having this error, please help!

Traceback (most recent call last):
  File "email_verifyer.py", line 10, in <module>
    email = valid.email
AttributeError: 'dict' object has no attribute 'email'

**Comment by JoshData** [comment]
I think you may have an earlier version of the package installed than what the documentation on GitHub is for.

On August 16, 2020 5:35:49 PM EDT, Faisal Ali Garba <notifications@github.com> wrote:
>I am having this error, please help!
>
>Traceback (most recent call last):
>  File "email_verifyer.py", line 10, in <module>
>    email = valid.email
>AttributeError: 'dict' object has no attribute 'email'
>
> 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JoshData/python-email-validator/issues/53

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
