### ISSUE TITLE
Idea: cache successful dns lookups?

### ISSUE THREAD

**Issue by HeyHugo** [JoshData/python-email-validator#55]
Would it make sense to cache (in memory) dns records that got a match to prevent a large amount of dns lookups for common email providers like gmail.com, hotmail.com etc?

If also caching non matches is fine `functools.lru_cache` decorator could be added to validate_email_deliverability, otherwise some custom logic could be written to keep a small cache of recent valid domains.

What do you think? I could probably make a PR if you like it?

**Comment by JoshData** [comment]
It makes sense. But the caller should have control over the cache lifetime -- it shouldn't be global or held in memory forever.

**Comment by HeyHugo** [comment]
I think a LRU type of cache would be quite fitting. It'd mean frequent occurring domains would stay in cache most of the time.
I'm thinking something quite simple like this could work: https://gist.github.com/damzam/4b0812c997e91f1bed17

With that said if you like the idea of having it timeout based instead I'm not opposed. That could work by storing each domain together with a timestamp. Cleanup of expired records could be done when encountering an expired domain.

What do you say, LRU cache or timeouts, should I make a PR?

**Comment by JoshData** [comment]
The best way would probably be to have the user pass in a dnsresolver cache object (https://dnspython.readthedocs.io/en/stable/resolver-caching.html) and then pass that to the resolver.

**Comment by HeyHugo** [comment]
Ah neat so dnspython has built in caching support. Makes sense to use that then 👍
