### ISSUE TITLE
DeprecationWarning: please use dns.resolver.resolve() instead

### ISSUE THREAD

**Issue by ThiefMaster** [JoshData/python-email-validator#56]
dnspython 2.0 deprecated it in favor of `.resolve(..., search=True)` and unfortunately this library does not pin the upper version of dnspython (a pin that excludes major version bumps is usually a good idea).

I think the best solution would be to release a version 2.0 of this library that requires dnspython 2.0 and drops python 2 support and uses the non-deprecated API.

**Comment by JoshData** [comment]
This is actually already fixed in #46 but I just haven't posted a new version to pypi, which I should do!

**Comment by JoshData** [comment]
It's uploaded to pypi now.
