### ISSUE TITLE
Question/Suggestion: functionality to suggest corrections?

### ISSUE THREAD

**Issue by caljess599** [JoshData/python-email-validator#59]
This is so recent and so thorough... I thought I'd ask if you had any thought about adding functionality to suggest common fixes when the error is quite evident, e.g., when someone types `.comn` or `@gamil.com`. I'm working with an API that rejects emails it knows are invalidated; what I need is a python tool that will suggest fixes. This is implemented in a ruby library (https://github.com/maximeg/email_inquire) and it probably wouldn't be too terrible to port this functionality over here...

**Comment by JoshData** [comment]
I'm not actively working on this project, but I'd accept pull requests with focused changes that don't create a maintenance burden for me.

That said, I'm not sure that detecting common errors are a good fit here. For example, @gamil.com could be a valid email address (it's a real domain name not owned by google) even if it might be a common error. I'd also prefer to not go down a path where we're guessing the common errors and adding code without a clear basis in reality.
