### ISSUE TITLE
Question about the validation

### ISSUE THREAD

**Issue by Erica-Ko** [JoshData/python-email-validator#62]
Dear contributors,
Is the package capable of 1) detecting the catch-all property of the email server and 2) email spam traps?
Thank you!

**Comment by JoshData** [comment]
I am not going to answer questions about circumventing anti-spam practices.

**Comment by Erica-Ko** [comment]
I see. Thanks for your response. I just wanna make it clear that I just try to validate the email address but not sending any spam email and that's why I ask about that.
