### ISSUE TITLE
email with slash char passed validations

### ISSUE THREAD

**Issue by DavidVaanunuLemonade** [JoshData/python-email-validator#63]
This email pattern - "a/b@domain.com" passes regex validations when it shouldn't (slash at the middle of the local part)
weirdly it also passes deliverability validations.
Unfortunately, I can't share the original email.

**Comment by JoshData** [comment]
If it's passing validation.... it's probably valid. Is there something you can point to that would demonstrate that it is not valid?

**Comment by DavidVaanunuLemonade** [comment]
So the char "/" in an email address considers legit?

**Comment by HeyHugo** [comment]
Yes ```!#$%&'*+-/=?^_`{|}~``` all those are valid in the local part it seems:
https://en.wikipedia.org/wiki/Email_address#Local-part

**Comment by DavidVaanunuLemonade** [comment]
Thanks for responding, weirdly enough that address pattern was not accepted by Facebook conversion API.
I'll open a ticket with them.
