### ISSUE TITLE
ModuleNotFoundError: No module named 'DNS'

### ISSUE THREAD

**Issue by yuchdev** [JoshData/python-email-validator#70]
Target OS: MacOS BigSur
Python version: 3.9.7 (Homebrew)
`email_validator` is installed alongside with other modules by `pip3 install -r requirements.txt` command

I receive `ModuleNotFoundError: No module named 'DNS'` on an attempt to import email_validator
`from email_validator import validate_email, EmailNotValidError`

Stacktrace: 
```
  File "/Users/atatat/Projects/LocalServer/mock_server/request_validator.py", line 7, in <module>
    from email_validator import validate_email, EmailNotValidError
  File "/usr/local/lib/python3.9/site-packages/email_validator/__init__.py", line 6, in <module>
    import dns.resolver
  File "/usr/local/lib/python3.9/site-packages/dns/__init__.py", line 27, in <module>
    from .Base import DnsRequest
  File "/usr/local/lib/python3.9/site-packages/dns/Base.py", line 45, in <module>
    from . import Lib
  File "/usr/local/lib/python3.9/site-packages/dns/Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
```

I tried to import module DNS manually, with the same result

```
ERROR: Could not find a version that satisfies the requirement DNS (from versions: none)
ERROR: No matching distribution found for DNS
```

**Comment by JoshData** [comment]
It looks like you have a conflicting package py3dns installed instead of (or in addition to?) dnspython. You would have to remove py3dns and possibly remove and reinstall dnspython. But if you have py3dns, it might be required by some other package that you are using, and so you might be stuck and can't have both.

**Comment by yuchdev** [comment]
Thank you for the insight, py3dns is really required by other packages. You can close the issue, or add some kind of diagnostic in your module (try to import something from py3dns, if `ModuleNotFoundError` is not raised, it seems to be installed and conflicting with your package)

**Comment by JoshData** [comment]
Ok. Good thought. (I'm not going to do that now but I'll keep it in mind.)
