### ISSUE TITLE
Unicode surrogates in local part

### ISSUE THREAD

**Issue by Pentusha** [JoshData/python-email-validator#72]
This email has to be invalid: `\udcff@example.com`.
This validation has already been implemented for the domain part.

**Comment by JoshData** [comment]
How do you know it is supposed to be invalid?

**Comment by Pentusha** [comment]
This is a reasonable question. Some other validation libraries mark this kind of email as invalid, so I decided that is the correct behavior.

**Comment by JoshData** [comment]
It's a good question. There may be a bigger class of Unicode strings that may be unsafe in some manner. For example, recently this: https://krebsonsecurity.com/2021/11/trojan-source-bug-threatens-the-security-of-all-code/. For the use case for this library, I think we can take a fairly strict approach and try to ensure that the local part of the address is safely displayable.

**Comment by JoshData** [comment]
Fixed by df852f7e380745b5d9612c274a9de4d8cd641c79 and b255f9eb80b1fbe956eeba72e0b4e4fa48c7dfd8. Thanks!
