### ISSUE TITLE
Using plus sign in a local part

### ISSUE THREAD

**Issue by Sanchoyzer** [JoshData/python-email-validator#74]
```python
>>> from email_validator import validate_email
>>> validate_email("+1@google.com")
<ValidatedEmail +1@google.com>
```
As far I know, a part between `+` and `@` will be dropped, so emails `abc+1@google.com` and `abc@google.com` are the same. 
That's why I'm not sure that emails like `+1@google.com` are valid.

**Comment by JoshData** [comment]
Many providers do that, but it's not a requirement, so it could be an actual email address.

**Comment by Sanchoyzer** [comment]
Ok, thanks
