### ISSUE TITLE
validate_email returns "The domain name xxx.xxx does not exist." for valid emails

### ISSUE THREAD

**Issue by dnaeye** [JoshData/python-email-validator#76]
I've run validate_email on my own email addresses, which have outlook.com and google.com domains, and I keep getting error messages saying that these domain names don't exist. Is this package broken?

**Comment by JoshData** [comment]
You might have a local or temporary DNS issue?

**Comment by dnaeye** [comment]
Ah, thanks for the thought! I disabled my VPN and now it works! Thank you for such a useful package!

**Comment by JoshData** [comment]
Thanks!
