### ISSUE TITLE
Correct email marked as invalid

### ISSUE THREAD

**Issue by stahh** [JoshData/python-email-validator#79]
from email_validator import validate_email, EmailNotValidError

def is_valid_email(email):
    try:
        # Validate.
        _ = validate_email(email)
        return True
    except EmailNotValidError:
        return False

print(is_valid_email('t.kalmuk@morshynska.com'))

**Comment by JoshData** [comment]
morshynska.com is either having a DNS outage or it is not a real domain name.

**Comment by stahh** [comment]
Thank you
