### ISSUE TITLE
The domain name gmail.com does not exist?

### ISSUE THREAD

**Issue by april-gm** [JoshData/python-email-validator#80]
First of all, thank you for developing a the useful lib for us. 

As a new python programmer, I trying to run test code you provided on readme page with a valid email as in the below code:

```
from email_validator import validate_email, EmailNotValidError

if __name__ == '__main__':

    email = "*********@gmail.com"

    try:
        # Validate & take the normalized form of the email
        # address for all logic beyond this point (especially
        # before going to a database query where equality
        # does not take into account normalization).
        email = validate_email(email).email
    except EmailNotValidError as e:
        # email is not valid, exception message is human-readable
        print(str(e))
```

This result is 
`The domain name gmail.com does not exist.`

Do I miss any additional setting to make the validator run properly? Please advice me and thank you in advanced.

**Comment by LocalsGitHub** [comment]
same issue here

**Comment by LocalsGitHub** [comment]
> Domain name validation failures are probably from a local DNS issue.
Could you point us in the right direction? What steps should we take to fix this?

**Comment by LocalsGitHub** [comment]
I need the DNS checking feature unfournately. Is there a way to fix whatever is wrong with my DNS?

**Comment by JoshData** [comment]
I'm sorry but since there's nothing to indicate the problem is something I can fix in this library, I won't be of any help with that.
