### ISSUE TITLE
TEST_ENVIRONMENT attribute not working with Python 3.9.12

### ISSUE THREAD

**Issue by jaredmolson** [JoshData/python-email-validator#81]
Hello. I am attempting to use the `TEST_ENVIRONMENT` module-level attribute in order to skip email validation in unit tests, but it does not appear to be working as expected. To test it, I created a fresh virtual environment, loaded in just `email-validator` and then opened a new shell, using Python 3.9.12. Below is the set of commands I ran and the traceback I received. It is my understanding that `TEST_ENVIRONMENT=True` should skip all DNS checks, but that is not what I am seeing. I also did this with `CHECK_DELIVERABILITY=False` and got the same unexpected DNS check behavior.

> Python 3.9.12 (main, Mar 26 2022, 15:51:15)
> [Clang 13.1.6 (clang-1316.0.21.2)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> \>\>\> import email_validator
> \>\>\> email = "test@123.com"
> \>\>\> email_validator.TEST_ENVIRONMENT
> False
> \>\>\> email_validator.TEST_ENVIRONMENT = True
> \>\>\> email_validator.TEST_ENVIRONMENT
> True
> \>\>\> email_validator.validate_email(email)
> Traceback (most recent call last):
>   File "/Users/Jared/test/lib/python3.9/site-packages/email_validator/__init__.py", line 616, in validate_email_deliverability
>     response = dns_resolver_resolve_shim(domain, "MX")
>   File "/Users/Jared/test/lib/python3.9/site-packages/email_validator/__init__.py", line 595, in dns_resolver_resolve_shim
>     return dns_resolver.resolve(domain, record)
>   File "/Users/Jared/test/lib/python3.9/site-packages/dns/resolver.py", line 1053, in resolve
>     (request, answer) = resolution.next_request()
>   File "/Users/Jared/test/lib/python3.9/site-packages/dns/resolver.py", line 632, in next_request
>     raise NXDOMAIN(qnames=self.qnames_to_try,
> dns.resolver.NXDOMAIN: The DNS query name does not exist: 123.com.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/Jared/test/lib/python3.9/site-packages/email_validator/__init__.py", line 631, in validate_email_deliverability
>     response = dns_resolver_resolve_shim(domain, "A")
>   File "/Users/Jared/test/lib/python3.9/site-packages/email_validator/__init__.py", line 595, in dns_resolver_resolve_shim
>     return dns_resolver.resolve(domain, record)
>   File "/Users/Jared/test/lib/python3.9/site-packages/dns/resolver.py", line 1053, in resolve
>     (request, answer) = resolution.next_request()
>   File "/Users/Jared/test/lib/python3.9/site-packages/dns/resolver.py", line 632, in next_request
>     raise NXDOMAIN(qnames=self.qnames_to_try,
> dns.resolver.NXDOMAIN: The DNS query name does not exist: 123.com.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/Jared/test/lib/python3.9/site-packages/email_validator/__init__.py", line 638, in validate_email_deliverability
>     response = dns_resolver_resolve_shim(domain, "AAAA")
>   File "/Users/Jared/test/lib/python3.9/site-packages/email_validator/__init__.py", line 595, in dns_resolver_resolve_shim
>     return dns_resolver.resolve(domain, record)
>   File "/Users/Jared/test/lib/python3.9/site-packages/dns/resolver.py", line 1053, in resolve
>     (request, answer) = resolution.next_request()
>   File "/Users/Jared/test/lib/python3.9/site-packages/dns/resolver.py", line 632, in next_request
>     raise NXDOMAIN(qnames=self.qnames_to_try,
> dns.resolver.NXDOMAIN: The DNS query name does not exist: 123.com.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/Jared/test/lib/python3.9/site-packages/email_validator/__init__.py", line 356, in validate_email
>     deliverability_info = validate_email_deliverability(
>   File "/Users/Jared/test/lib/python3.9/site-packages/email_validator/__init__.py", line 645, in validate_email_deliverability
>     raise EmailUndeliverableError("The domain name %s does not exist." % domain_i18n)
> email_validator.EmailUndeliverableError: The domain name 123.com does not exist.

**Comment by JoshData** [comment]
Ok yeah I guess I messed it up and didn't test it. Whelp. Next release.

**Comment by JoshData** [comment]
Should be fixed in c7548b3ed75f5c4866835be3759b17bfa102d53f on the `dev` branch.
