### ISSUE TITLE
EmailUndeliverableError when check_deliverability=False

### ISSUE THREAD

**Issue by 0xdade** [JoshData/python-email-validator#82]
I was doing some mass analysis of email addresses attached to pypi packages and I encountered a behavior that seems unexpected. When specifically setting `check_deliverability=False`, I would have expected to only check the validity of the _syntax_ of the address, and therefore only receive an `EmailSyntaxError` if the syntax is invalid. Instead, if I pass in a reserved TLD, I get an `EmailUndeliverableError` even though I explicitly am asking to not validate the deliverability of the email.

I think the expected behavior should be to only include this specific `EmailUndeliverableError` if `check_deliverability=True`, or otherwise to change the exception raised to an `EmailSyntaxError` if this should be considered a syntax error. I'm inclined to think the former is more in line with expectations, but `.invalid` is probably declared in the RFC as an invalid TLD for email use which could debatably be considered a Syntax error?

## Reproduction

```python
>>> from email_validator import validate_email
>>> validate_email("dade@gitlab.invalid", check_deliverability=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dade/github/0xdade/spypi/.venv/lib/python3.9/site-packages/email_validator/__init__.py", line 303, in validate_email
    domain_part_info = validate_email_domain_part(parts[1], test_environment=test_environment)
  File "/Users/dade/github/0xdade/spypi/.venv/lib/python3.9/site-packages/email_validator/__init__.py", line 559, in validate_email_domain_part
    raise EmailUndeliverableError("The domain name %s is a special-use or reserved name that cannot be used with email." % domain_i18n)
email_validator.EmailUndeliverableError: The domain name gitlab.invalid is a special-use or reserved name that cannot be used with email.
```

**Comment by 0xdade** [comment]
I admit I came here and opened this ticket before reading the latest readme and seeing that this is intentional behavior, and that I can just remove the values from the `SPECIAL_USE_DOMAIN_NAMES` if I need to consider them valid. I think this is sufficient for my use case, but do find it kind of confusing to get deliverability errors when explicitly saying "Do not check for deliverability errors".

**Comment by JoshData** [comment]
I agree that the exception type is a bit confusing. Something to consider for the next update. 👍
