### ISSUE TITLE
Continuous fuzzing of python-email-validator by way of OSS-Fuzz

### ISSUE THREAD

**Issue by manunio** [JoshData/python-email-validator#84]
Given the popularity of python-email-validator, I was thinking that it would be nice to set up continuous fuzzing of python-email-validator, by way of OSS-Fuzz. In this PR: https://github.com/google/oss-fuzz/pull/8107 I have done exactly that, namely created the necessary logic from an OSS-Fuzz perspective to integrate python-email-validator. This includes developing initial fuzzers as well as integrating into OSS-Fuzz.

Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects. The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is if bugs are not fixed then it is a waste of resources to run the fuzzers, which we would like to avoid.

If you would like to integrate, could I please have an email(s), it must be associated with a Google account like gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by manunio** [comment]
@JoshData friendly ping :)

**Comment by JoshData** [comment]
Hi. Since this is a pure python library, I don't really understand what sorts of bugs _in this repository_ (i.e. not a dependency) this might reveal. And if the fuzzer is run once now, does it report any issues?

**Comment by manunio** [comment]
> Hi. Since this is a pure python library, I don't really understand what sorts of bugs _in this repository_ (i.e. not a dependency) this might reveal. And if the fuzzer is run once now, does it report any issues?

Hi Josh, with my initial assessment by running fuzzer locally for few minutes i did find an issue, but i'm not sure what the root cause is, maybe its because of my local dns or something else but few inputs to validate_email() were taking 10s to 30s before raising  EmailUndeliverableError exception.

**Comment by JoshData** [comment]
What I'm trying to figure out here is if this is going to end up opening a lot of misdirected or spurious issues --- i.e. is this going to create new busywork for me. Before adding this project to OSS-Fuzz, I would ask you to try to sort through any issues that are going to arise immediately. If you think there might be a bug with the fuzzed inputs you generate, feel free to list them here and we can work through it.

**Comment by manunio** [comment]
> What I'm trying to figure out here is if this is going to end up opening a lot of misdirected or spurious issues --- i.e. is this going to create new busywork for me.

Hi Josh, thanks for raising valid points, as a new contributor to oss-fuzz i was not sure how to address this and asked the oss-fuzz team for their thoughts,
but based on past projects integrated into oss-fuzz  here is what i think,

Yes there is a chance for it raising such issues but its less likely,  as all this fuzzer is doing right now is testing email-validator against random inputs, 
which we can fine tune it to reduce noise and see that it only raises valid reports, and in the end if you are still not convinced that this integration is helping you, we can disable project at oss-fuzz.

>  Before adding this project to OSS-Fuzz, I would ask you to try to sort through any issues that are going to arise immediately. If you think there might be a bug with the fuzzed inputs you generate, feel free to list them here and we can work through it.

for this i'ill have to run it locally or via other medium, It will be hard for me to run it locally, as inputs are random hence chance of initial assessment issues occurring again are random too,  and running fuzzer for long time is resource intensive, so i believe best place for that is oss-fuzz with their continuous fuzzing.

if you are still interested, please let me know :)

**Comment by JoshData** [comment]
That sounds like a great solution. Yes, please go ahead. :)
