### ISSUE TITLE
I want to know whether the email actually exists

### ISSUE THREAD

**Issue by joshuajaistein** [JoshData/python-email-validator#87]
Hi Josh , I was using Abstract API for email validation and verification , but I found your pypi library to do it myself. I read through the page but I can't figure it out to code the feature. For a given email I just want to check whether it's deliverable or not. Can you give a small snippet ? It would greatly help.Thank you.

**Comment by JoshData** [comment]
Hello. There is an example near the top of the README. Do you have a more specific question?

**Comment by joshuajaistein** [comment]
Here is it ... (check_deliverability = True) checks for the domain existence . However I want to know whether the email actually exists.

Eg:

CASE 1:
input a valid , existing email
joshuajaistein@gmail.com = True

CASE 2:
let me try another non-existent email like say , 

joshua88jaistein@gmail.com is still True , while such mail doesn't exist at all....

How to resolve this ?

**Comment by JoshData** [comment]
There is no way to know whether an email address delivers to a mailbox other than by emailing it and asking the recipient to click a link or take some other action you can observe. For that reason, it is outside of the scope of this project.
