### ISSUE TITLE
1.3.0 not compatible with python 2.7

### ISSUE THREAD

**Issue by cormachallinanderilinx** [JoshData/python-email-validator#91]
We deployed an application of ours which is still using python2.7 and pulls in the latest version of email-validator, the version 1.3.0 cause our application to crash.

See log:
`
File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/email_validator/__init__.py", line 255
def caching_resolver(*, timeout=None, cache=None):
                                     ^
 SyntaxError: invalid syntax
`

The * in a function definition was only introduced in python3.

Reading your pypi docs it states python 2.7 or greater is supported
`Requires: Python !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, >=2.7`

**Comment by JoshData** [comment]
I would recommend pinning to the last compatible version of this library. The only changes are some enhancements. I can update the README to reflect that recent versions are 3.x-only.

**Comment by lovette** [comment]
This one bit me yesterday too. Guess that's on me for not pinning all my dependencies! But deprecating support for Python 2 seems like a bit more than an "enhancement" to me 😁 I didn't expect that big a change to be introduced in a point release. A deprecation notice in the README would definitely have saved me some headache.

**Comment by JoshData** [comment]
I updated the README and CHANGELOG.
