### ISSUE TITLE
Email addresses with U+2026 '…' in the local part are marked as valid

### ISSUE THREAD

**Issue by trunova-d** [JoshData/python-email-validator#96]
Hello! I just ran into a problem while testing. Emails like `CAT…123@email.com`(with multiple dots) marked as valid.
Test:
```
import pytest
from email_validator import validate_email, EmailSyntaxError


@pytest.mark.parametrize('email', [
    'example…example@email.com',
    'CAT…123@email.com',
    'obviously"not"correct@email.com'
])
def test_failed(email):
    with pytest.raises(EmailSyntaxError):
        validate_email(email)
```

Result:

<img width="1205" alt="Снимок экрана 2023-02-06 в 12 15 20" src="https://user-images.githubusercontent.com/124560505/216945762-5e4ee4f8-7bf5-4605-9d50-a3f740aa3984.png">

**Comment by JoshData** [comment]
Hi.

You've got the Unicode character "Horizontal Ellipsis" U+2026 in there (so, not three ASCII dots).

As far as I'm aware, pretty much any non-ASCII Unicode character is allowed in the local part. Is there a specific reason why you think it's not valid (other than a gut feeling)?
