### ISSUE TITLE
Support python 3.11

### ISSUE THREAD

**Issue by henrikstranneheim** [JoshData/python-email-validator#97]
Thank you for a great tool. Are you planning to support `Python :: 3.11` in the near future?

**Comment by JoshData** [comment]
I just added it to setup.cfg. Thanks. There was some problem but I can't reproduce the problem now, so I'll just go ahead and hope there's no real problem. :)

**Comment by henrikstranneheim** [comment]
@JoshData Thx I will give it a try

**Comment by henrikstranneheim** [comment]
Will you also make a new Pypi release?

**Comment by JoshData** [comment]
There are a lot of other recent changes so I like to hold off in the hopes that someone else might be watching/testing the main branch.
